-- Supabase Database Schema for My Stock Dashboard

-- 1. account_summary table
CREATE TABLE IF NOT EXISTS public.account_summary (
    account_name text NOT NULL PRIMARY KEY,
    eval_total bigint DEFAULT 0,
    invest_total bigint DEFAULT 0,
    profit bigint DEFAULT 0,
    return_rate double precision DEFAULT 0.0,
    daily_change_pct double precision DEFAULT 0.0,
    daily_change_amt bigint DEFAULT 0,
    dividend bigint DEFAULT 0,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 2. holdings table
CREATE TABLE IF NOT EXISTS public.holdings (
    ticker text NOT NULL,
    account_name text NOT NULL,
    stock_name text NOT NULL,
    quantity double precision DEFAULT 0.0,
    avg_price double precision DEFAULT 0.0,
    currency text DEFAULT 'KRW',
    current_price double precision DEFAULT 0.0,
    eval_krw double precision DEFAULT 0.0,
    profit double precision DEFAULT 0.0,
    return_rate double precision DEFAULT 0.0,
    weight double precision DEFAULT 0.0,
    daily_change double precision DEFAULT 0.0,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    PRIMARY KEY (ticker, account_name)
);

-- 3. asset_history table
CREATE TABLE IF NOT EXISTS public.asset_history (
    record_date date NOT NULL PRIMARY KEY,
    eval_total bigint DEFAULT 0,
    invest_total bigint DEFAULT 0,
    profit bigint DEFAULT 0,
    dividend bigint DEFAULT 0,
    usd_krw_rate double precision DEFAULT 1300.0,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 4. transactions table
CREATE TABLE IF NOT EXISTS public.transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date date NOT NULL,
    stock_name text NOT NULL,
    stock_code text NOT NULL,
    currency text DEFAULT 'KRW',
    type text NOT NULL, -- '매수', '매도', '배당금', '입출금' 등
    quantity double precision DEFAULT 0.0,
    price double precision DEFAULT 0.0,
    account text NOT NULL,
    usd_krw_rate double precision DEFAULT 1.0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- RLS (Row Level Security) 설정
-- 프론트엔드에서는 anon 키만 사용하므로, 읽기 전용 + transactions INSERT만 허용
ALTER TABLE public.account_summary ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.holdings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.asset_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

-- account_summary: anon은 읽기만 허용 (쓰기는 service_role인 update_prices.py에서만)
CREATE POLICY "anon_select_account_summary" ON public.account_summary
  FOR SELECT TO anon USING (true);

-- holdings: anon은 읽기만 허용 (쓰기/삭제는 service_role인 update_prices.py에서만)
CREATE POLICY "anon_select_holdings" ON public.holdings
  FOR SELECT TO anon USING (true);

-- asset_history: anon은 읽기만 허용 (쓰기는 service_role인 update_prices.py에서만)
CREATE POLICY "anon_select_asset_history" ON public.asset_history
  FOR SELECT TO anon USING (true);

-- transactions: anon은 읽기 + 신규 삽입 허용 (수정/삭제 불가)
CREATE POLICY "anon_select_transactions" ON public.transactions
  FOR SELECT TO anon USING (true);

CREATE POLICY "anon_insert_transactions" ON public.transactions
  FOR INSERT TO anon WITH CHECK (true);
