-- Supabase Database Schema for My Stock Dashboard

-- 1. account_summary table
CREATE TABLE IF NOT EXISTS public.account_summary (
    account_name text NOT NULL PRIMARY KEY,
    eval_total bigint DEFAULT 0,
    invest_total bigint DEFAULT 0,
    profit bigint DEFAULT 0,
    return_rate double precision DEFAULT 0.0,
    daily_change_pct double precision DEFAULT 0.0,
    daily_change_amt bigint DEFAULT 0,
    dividend bigint DEFAULT 0,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 2. holdings table
CREATE TABLE IF NOT EXISTS public.holdings (
    ticker text NOT NULL,
    account_name text NOT NULL,
    stock_name text NOT NULL,
    quantity double precision DEFAULT 0.0,
    avg_price double precision DEFAULT 0.0,
    currency text DEFAULT 'KRW',
    current_price double precision DEFAULT 0.0,
    eval_krw double precision DEFAULT 0.0,
    profit double precision DEFAULT 0.0,
    return_rate double precision DEFAULT 0.0,
    weight double precision DEFAULT 0.0,
    daily_change double precision DEFAULT 0.0,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    PRIMARY KEY (ticker, account_name)
);

-- 3. asset_history table
CREATE TABLE IF NOT EXISTS public.asset_history (
    record_date date NOT NULL PRIMARY KEY,
    eval_total bigint DEFAULT 0,
    invest_total bigint DEFAULT 0,
    profit bigint DEFAULT 0,
    dividend bigint DEFAULT 0,
    usd_krw_rate double precision DEFAULT 1300.0,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 4. transactions table
CREATE TABLE IF NOT EXISTS public.transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date date NOT NULL,
    stock_name text NOT NULL,
    stock_code text NOT NULL,
    currency text DEFAULT 'KRW',
    type text NOT NULL, -- '매수', '매도', '배당금', '입출금' 등
    quantity double precision DEFAULT 0.0,
    price double precision DEFAULT 0.0,
    account text NOT NULL,
    usd_krw_rate double precision DEFAULT 1.0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- RLS (Row Level Security) 설정
ALTER TABLE public.account_summary DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.holdings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.asset_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions DISABLE ROW LEVEL SECURITY;
